{% set name = "findpython" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: 80557961c04cf1c8c4ba4ca3ac7cf76ec27fa92788a6af42cb701e3450c49430

build:
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - findpython = "findpython.__main__:main"

requirements:
  host:
    - pip
    - python
    - pdm-pep517
    - setuptools
    - wheel
  run:
    - packaging >=20
    - python

test:
  imports:
    - findpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/findpython/
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
