{% set name = "findpython" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: 8b31647c76352779a3c1a0806699b68e6a7bdc0b5c2ddd9af2a07a0d40c673dc

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - findpython = findpython.__main__:main

requirements:
  host:
    - pip
    - python
    - pdm-backend
  run:
    - python
    - packaging >=20
    - platformdirs >=4.3.6

test:
  source_files:
    - tests
  imports:
    - findpython
    - findpython.finder
    - findpython.providers
    - findpython.providers.asdf
    - findpython.providers.base
    - findpython.providers.macos
    - findpython.providers.path
    - findpython.providers.pyenv
    - findpython.providers.rye
    - findpython.providers.uv
    - findpython.providers.winreg
    - findpython.python
    - findpython.utils
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/frostming/findpython
  description: |
    This library is a rewrite of pythonfinder project by @techalchemy.
    It simplifies the whole code structure while preserving most of the original features.
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/frostming/findpython
  doc_url: https://github.com/frostming/findpython/blob/main/README.md

extra:
  recipe-maintainers:
    - xhochy