{% set name = "findpython" %}
{% set version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53b32264874dfa5990bd09d717819386d8db3149d89fe20f88fe1078de286bae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - findpython = findpython.__main__:main
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - pdm-backend
  run:
    - python
    - packaging >=20
    - platformdirs >=4.3.6

test:
  source_files:
    - tests
  imports:
    - findpython
    - findpython.finder
    - findpython.providers
    - findpython.providers.asdf
    - findpython.providers.base
    - findpython.providers.macos
    - findpython.providers.path
    - findpython.providers.pyenv
    - findpython.providers.rye
    - findpython.providers.uv
    - findpython.providers.winreg
    - findpython.python
    - findpython.utils
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/frostming/findpython
  description: |
    This library is a rewrite of pythonfinder project by @techalchemy.
    It simplifies the whole code structure while preserving most of the original features.
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/frostming/findpython
  doc_url: https://github.com/frostming/findpython/blob/main/README.md

extra:
  recipe-maintainers:
    - xhochy